# Generated by Django 4.2.1 on 2023-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_departamento', '0002_alter_departamento_options_and_more'),
        ('persona', '0002_habilidades_alter_persona_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('first_name', 'departamento')},
        ),
        migrations.AddField(
            model_name='persona',
            name='habilidades',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
    ]
