# Generated by Django 4.2.1 on 2023-05-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['first_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Recursos laborales'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'last_name')},
        ),
    ]
